---
name: "loaddbalarms"
description: "Get HPECFM alarms and load mongo databases."
enabled: true

trigger:
  type: "core.st2.IntervalTimer"
  parameters:
    delta: 5
    unit: minutes

action:
  ref: "hpecfmaudits.getalarmstoload"
